name: Deploy

on:
  push:
    branches: [master]
    paths:
      - functions/**
      - firestore.rules
      - firestore.indexes.json
      - storage.rules

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Web app Dependencies
        run: yarn --frozen-lockfile

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --except hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
